project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

website:
  title: "Soumik Purkayastha"
  description: "Assistant Professor of Biostatistics & Health Data Science, University of Pittsburgh"
  site-url: "https://soumikp.github.io"
  reader-mode: false
  search: false

format:
  html:
    theme: none
    css: styles.css
    page-layout: custom
    toc: false
    anchor-sections: false
    smooth-scroll: true
    include-in-header:
      text: |
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    include-before-body: includes/nav.html
    include-after-body: includes/footer.html
